# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-18 14:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VendRetailer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True)),
                ('access_token', models.CharField(max_length=256)),
                ('expires', models.DateTimeField()),
                ('expires_in', models.IntegerField()),
                ('refresh_token', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='VendUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(editable=False)),
                ('name', models.CharField(max_length=256)),
                ('display_name', models.CharField(max_length=256)),
                ('image', models.URLField(blank=True)),
                ('account_type', models.CharField(choices=[('A', 'Admin'), ('M', 'Manager'), ('C', 'Cashier')], default='C', max_length=1)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('retailer', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='vend_auth.VendRetailer')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
