# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-24 18:19
from __future__ import unicode_literals

from django.db import migrations, models

from django_vend.core.utils import get_vend_setting

DEFAULT_USER_IMAGE = get_vend_setting('VEND_DEFAULT_USER_IMAGE')


class Migration(migrations.Migration):

    dependencies = [
        ('vend_auth', '0002_venduser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venduser',
            name='image',
            field=models.URLField(blank=True, default=DEFAULT_USER_IMAGE),
        ),
    ]
