# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-24 21:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def make_venduser_and_vendretailer_m2m_users(apps, schema_editor):
    VendUser = apps.get_model('vend_auth', 'venduser')
    VendRetailer = apps.get_model('vend_auth', 'vendretailer')
    for vu in VendUser.objects.all():
        if vu.user:
            vu.retailer.users.add(vu.user)
            vu.users.add(vu.user)

class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vend_auth', '0003_auto_20161224_1819'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('retailer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vend_auth.VendRetailer')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='venduser',
            name='users',
            field=models.ManyToManyField(related_name='vendusers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vendretailer',
            name='users',
            field=models.ManyToManyField(related_name='retailer', through='vend_auth.VendProfile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(
            make_venduser_and_vendretailer_m2m_users
        ),
    ]
