# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-24 21:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vend_auth', '0004_auto_20161224_2152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venduser',
            name='user',
        ),
    ]
