# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-25 20:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vend_auth', '0005_remove_venduser_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendretailer',
            name='users',
        ),
        migrations.AlterField(
            model_name='vendprofile',
            name='retailer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendprofile', to='vend_auth.VendRetailer'),
        ),
        migrations.AlterField(
            model_name='vendprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vendprofile', to=settings.AUTH_USER_MODEL),
        ),
    ]
