# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-25 20:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


def add_vendusers_to_vendprofiles(apps, schema_editor):
    VendUser = apps.get_model('vend_auth', 'venduser')
    VendProfile = apps.get_model('vend_auth', 'vendprofile')

    for vu in VendUser.objects.all():
        for u in vu.users.all():
            vp = VendProfile.objects.get(user=u)
            vp.vendusers.add(vu)

class Migration(migrations.Migration):

    dependencies = [
        ('vend_auth', '0006_auto_20161225_2043'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendprofile',
            name='vendusers',
            field=models.ManyToManyField(related_name='vendprofiles', to='vend_auth.VendUser'),
        ),
        migrations.AlterField(
            model_name='venduser',
            name='users',
            field=models.ManyToManyField(related_name='TO_REMOVE', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(
            add_vendusers_to_vendprofiles
        ),
    ]
