# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-29 12:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vend_stores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendoutlet',
            name='retrieved',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vendregister',
            name='retrieved',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
